<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout d'enseignant
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/administratif/ajoutProf"
                          method="post">
                        <div class="form-group">
                            <label for="nom">Nom:</label>
                            <input type="text" class="form-control" name="nom"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="prenom">Prénom:</label>
                            <input type="text" class="form-control"
                                   name="prenom" required>
                        </div>
                        <div class="form-group">
                            <label for="id">Identifiant (13 caractères):</label>
                            <input type="text" class="form-control" name="id"
                                   maxlength="13"
                                   minlength="13" required>
                        </div>
                        <div class="form-group">
                            <label for="tel">Téléphone:</label>
                            <input type="tel" class="form-control" name="tel"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="email">Adresse e-mail:</label>
                            <input type="email" class="form-control"
                                   name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="adresse">Adresse:</label>
                            <input type="text" class="form-control"
                                   name="adresse" required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   name="adresse2">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   name="adresse3">
                        </div>
                        <div class="form-group">
                            <label for="ville">Ville:</label>
                            <select class="form-control select" name="ville"
                                    required>
                                <?php
                                    foreach ($obj[0] as $ville) {
                                        ?>
                                        <option
                                            value="<?php echo $ville->getNumInsee(); ?>"> <?php echo $ville->getNom(); ?> </option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </div>
                        <button type="submit"
                                class="btn btn-success center-block">Créer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout de département
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/administratif/ajoutDep"
                          method="post">
                        <div class="form-group">
                            <label for="idDep">Identifiant du
                                département:</label>
                            <input type="text" class="form-control" name="idDep"
                                   maxlength="10" required>
                        </div>
                        <div class="form-group">
                            <label for="nomDep">Nom du département:</label>
                            <input type="text" class="form-control"
                                   name="nomDep" required>
                        </div>
                        <button type="submit"
                                class="btn btn-success center-block">Créer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout de promotion
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/administratif/ajoutPromo"
                          method="post">
                        <div class="form-group">
                            <label for="nomPromo">Nom de la promotion:</label>
                            <input type="text" class="form-control"
                                   name="nomPromo" required>
                        </div>
                        <div class="form-group">
                            <label for="anneePromo">Année de la
                                promotion:</label>
                            <input type="text" class="form-control"
                                   name="anneePromo" required>
                        </div>
                        <label for="depPromo">Département de la
                            promotion:</label>
                        <select class="form-control select" name="depPromo"
                                required>
                            <?php
                                foreach ($obj[1] as $deps) {
                                    ?>
                                    <option
                                        value="<?php echo $deps->getId(); ?>"> <?php echo $deps->getNom(); ?> </option>
                                    <?php
                                }
                            ?>
                        </select>
                        <button type="submit" class="btn btn-success center-block">Créer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
