<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;

?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            <?= $obj[0]->getNomComplet() ?>
        </div>
        <div class="panel-body">
            <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                <div class="row">
                    <div class="col-md-12 toolbar">
                        <div class="btn-group panel-body">
                            <a href="/SatellysReborn/administratif/supprimer/<?= $obj[0]->getId() ?>/"
                               class="btn btn-danger btn-lg"><i
                                    class="fa fa-remove"></i> Supprimer</a>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="id">Identifiant UT1 (13 caractères)
                            :</label>
                        <input type="text" id="id" name="id"
                               class="form-control"
                               placeholder="Identifiant" pattern="\w{13}"
                               value="<?= $obj[0]->getId() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-3">
                    <div class="form-group">
                        <label for="nom">Nom :</label>
                        <input type="text" id="nom" name="nom"
                               class="form-control" placeholder="Nom"
                               value="<?= $obj[0]->getNom() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="prenom">Nom :</label>
                        <input type="text" id="prenom" name="prenom"
                               class="form-control" placeholder="Prénom"
                               value="<?= $obj[0]->getPrenom() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-3 col-md-offset-3">
                    <div class="form-group">
                        <label for="tel">Téléphone :</label>
                        <input type="tel" id="tel" name="tel"
                               pattern="\d{10}"
                               class="form-control" placeholder="Téléphone"
                               value="<?= $obj[0]->getTel() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="email">Email :</label>
                        <input type="email" id="email" name="email"
                               class="form-control" placeholder="Email"
                               value="<?= $obj[1]->getEmail() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="poste">Poste
                            :</label>
                        <input type="text" id="poste" name="poste"
                               class="form-control"
                               placeholder="Poste"
                               value="<?= $obj[0]->getPoste() ?>"
                               readonly>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="adresse1">Adresse :</label>
                        <input type="text" id="adresse1" name="adresse1"
                               class="form-control" placeholder="Adresse"
                               value="<?= $obj[0]->getAdresse()
                                                 ->getAdresse1() ?>"
                               readonly>
                    </div>
                    <div class="form-group">
                        <input type="text" id="adresse2" name="adresse2"
                               class="form-control" placeholder="Adresse"
                               value="<?= $obj[0]->getAdresse()
                                                 ->getAdresse2() ?>" readonly>

                    </div>
                    <div class="form-group">
                        <input type="text" id="adresse3" name="adresse3"
                               class="form-control" placeholder="Adresse"
                               value="<?= $obj[0]->getAdresse()
                                                 ->getAdresse3() ?>" readonly>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">
                        <label for="ville">Ville :</label>
                        <select name="ville"
                                class="form-control select-ville"
                                id="ville" readonly>
                            <option
                                value="<?= $obj[0]->getAdresse()->getVille()
                                                  ->getNumInsee() ?>"><?= $obj[0]->getAdresse()
                                                                                 ->getVille()
                                                                                 ->getCodePostal() .
                                                                          ' - ' .
                                                                          $obj[0]->getAdresse()
                                                                                 ->getVille()
                                                                                 ->getNom() ?></option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>