<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur de remplissage
        </div>
        <div class="panel-body">
            Une erreur s'est produite lors du remplissage du formulaire.
            Veuillez remplir tout les champs !
        </div>
    </div>
</div>
