<?php
    include_once COMMON . 'header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Liste des administratifs
        </div>
        <div class="panel-body">
            <div class="container">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td>Login</td>
                            <td>Email</td>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($obj == null): ?>
                            <tr>
                                <td colspan="2" class="text-center">Aucuns administratif</td>
                            </tr>
                        <?php else: ?>
                            <?php foreach ($obj as $admin): ?>
                                <tr>
                                    <td>
                                        <a href="administratif/detail/<?= $admin->getLogin() ?>"><?= $admin->getLogin() ?></a>
                                    </td>
                                    <td>
                                        <?= $admin->getEmail() ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>