<?php
    include_once COMMON . 'header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <h1>Ajout de personnel administratif : </h1>
    <form action="ajout" method="post">
        <div class="form-group">
            <label for="nom">Nom:</label>
            <input type="text" class="form-control" name="nom" required>
        </div>
        <div class="form-group">
            <label for="prenom">Prénom:</label>
            <input type="text" class="form-control" name="prenom" required>
        </div>
        <div class="form-group">
            <label for="tel">Téléphone:</label>
            <input type="tel" class="form-control" name="tel" required>
        </div>
        <div class="form-group">
            <label for="email">Adresse e-mail:</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <div class="form-group">
            <label for="poste">Poste:</label>
            <input type="text" class="form-control" name="poste" required>
        </div>
        <div class="form-group">
            <label for="adresse">Adresse:</label>
            <input type="text" class="form-control" name="adresse" required>
        </div>
        <div class="form-group">
            <label for="ville">Ville:</label>
            <input type="text" class="form-control" name="ville" required>
            <label for="cp">Code Postal:</label>
            <input type="text" class="form-control" name="cp" required>
        </div>
        <button type="submit" class="btn btn-default">Créer</button>
    </form>
</div>
