<?php
    include_once COMMON . 'header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <h1>Ajout de personnel administratif : </h1>
    <form>
        <div class="form-group">
            <label for="nom">Nom:</label>
            <input type="text" class="form-control" id="nom">
        </div>
        <div class="form-group">
            <label for="prenom">Prénom:</label>
            <input type="text" class="form-control" id="prenom">
        </div>
        <div class="form-group">
            <label for="tel">Téléphone:</label>
            <input type="tel" class="form-control" id="tel">
        </div>
        <div class="form-group">
            <label for="email">Adresse e-mail:</label>
            <input type="email" class="form-control" id="email">
        </div>
        <div class="form-group">
            <label for="poste">Poste:</label>
            <input type="text" class="form-control" id="poste">
        </div>
        <div class="form-group">
            <label for="adresse">Adresse:</label>
            <input type="text" class="form-control" id="adresse">
        </div>
        <button type="submit" class="btn btn-default">Créer</button>
    </form>
</div>
