<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Impossible de supprimer cette matière
        </div>
        <div class="panel-body">
            Il est impossible de supprimer cette matière car elle est encore enseignée dans des cours.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>