<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Liste des groupes d'étudiants
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 toolbar">
                    <div class="btn-group">
                        <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                            <a href="/SatellysReborn/matiere/creation/"
                               class="btn btn-success btn-lg"><i
                                    class="fa fa-plus"></i> Nouveau</a>
                        <?php endif; ?>
                        <a href="#" id="mail"
                           class="btn btn-primary btn-lg"><i
                                class="fa fa-envelope-o"></i> Envoyer</a>
                    </div>
                </div>
            </div>
            <table data-toggle="table" data-search="true" data-height="800"
                   data-pagination="true" data-page-list="[10, 25, 50, 100, All]">
                <thead>
                <tr>
                    <th data-field="nom" data-sortable="true">Nom</th>
                    <th data-field="promo" data-sortable="true">Promotion</th>
                    <th data-field="dep" data-sortable="true">Département</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    if ($obj != null):
                        foreach ($obj as $matiere): ?>
                            <tr>
                                <td><a href="/SatellysReborn/matiere/details/<?= $matiere[0]->getId() ?>"><?= $matiere[0]->getNom() ?></a></td>
                                <?php if (isset($matiere[1])): ?>
                                    <td><a href="/SatellysReborn/promotion/details/<?= $matiere[1]->getId() ?>"><?= $matiere[1]->getNom() ?></a></td>
                                    <td><a href="/SatellysReborn/departement/details/<?= $matiere[1]->getDepartement()->getId() ?>"><?= $matiere[1]->getDepartement()->getNom() ?></a></td>
                                <?php else: ?>
                                    <td></td>
                                    <td></td>
                                <?php endif; ?>
                            </tr>
                        <?php endforeach;
                    endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>