<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Liste des cours
        </div>
        <div class="panel-body">
            <table data-toggle="table" data-height="800" data-search="true"
                   data-pagination="true">
                <thead>
                <tr>
                    <th data-sortable="true" data-field="date">Date</th>
                    <th data-sortable="true" data-field="heures">Heures</th>
                    <th data-sortable="true" data-field="enseignant">Enseignant</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($obj as $cours): ?>
                    <tr>
                        <td> <?= $cours->getJour(); ?>
                        <td> <?= $cours->getDebut() . ' - ' .
                                 $cours->getFin(); ?></td>
                        <td><?= $cours->getEnseignant()->getPrenom().' '.$cours->getEnseignant()->getNom(); ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
