<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Vous n'êtes pas autorisé à accéder à cette page.
        </div>
        <div class="panel-body">
            Vous devez être un administrateur ou un administratif pour accéder à cette page.
        </div>
    </div>
</div>