<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Impossible de trouver le fichier ICS
        </div>
        <div class="panel-body">
            Veuillez importer un fichier ICS avant d'essayer de l'enregistrer.
        </div>
    </div>
</div>