<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Importer un fichier ICS
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/import/preLoadICS/" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="ics">Fichier ICS :</label>
                            <input type="file" id="ics" name="ics" class="form-control" accept=".ics" required>
                        </div>
                        <input type="submit" class="btn btn-success center-block" value="Envoyer">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>