<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            Erreur : Problème dans l'importation du fichier ICS
        </div>
        <div class="panel-body">
            Une erreur est survenu durant l'importation du fichier ICS.<br/>
            Veuillez recommencer.
        </div>
    </div>
</div>