<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Créer un département
        </div>
        <div class="panel-body">
            <div class="row">
                <form action="/SatellysReborn/departement/creer/" method="post">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label for="nom">Nom :</label>
                            <input type="text" id="nom" name="nom"
                                   class="form-control"
                                   placeholder="Le nom du département"
                                   required>
                        </div>
                        <input type="submit"
                               class="btn btn-success center-block"
                               value="Créer">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>