<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Département <?= $obj[0]->getNom() ?>
        </div>
        <div class="panel-body">
            <form
                action="/SatellysReborn/departement/modifier/<?= $obj[0]->getId() ?>/"
                method="post">
                <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                    <div class="row">
                        <div class="col-md-12 toolbar">
                            <div class="btn-group">
                                <a href="/SatellysReborn/promotion/creation/<?= $obj[0]->getId() ?>/"
                                   class="btn btn-success btn-lg"><i
                                        class="fa fa-plus"></i> Ajouter une
                                    promotion</a>
                                <button type="submit" class="btn btn-info btn-lg"><i
                                        class="fa fa-edit"></i> Modifier
                                </button>
                                <a href="#" id="mail"
                                   class="btn btn-primary btn-lg"><i
                                        class="fa fa-envelope-o"></i> Envoyer</a>
                                <?php if (empty($obj[1])): ?>
                                    <a href="/SatellysReborn/departement/supprimer/<?= $obj[0]->getId() ?>/"
                                       class="btn btn-danger btn-lg"><i
                                            class="fa fa-remove"></i> Supprimer</a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="row">
                    <div class="col-md-3 col-md-offset-3">
                        <div class="form-group">
                            <label for="id">Identifiant :</label>
                            <input type="text" id="id" class="form-control"
                                   value="<?= $obj[0]->getId() ?>" readonly>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="nom">Nom :</label>
                            <input type="text" id="nom" name="nom"
                                   class="form-control" placeholder="Nom"
                                   value="<?= $obj[0]->getNom() ?>" required>
                        </div>
                    </div>
                </div>
            </form>
            <table data-toggle="table" data-search="true" data-height="800"
                   data-pagination="true">
                <thead>
                <tr>
                    <th data-field="nom" data-sortable="true">Nom</th>
                    <th data-field="annee" data-sortable="true">Année Scolaire</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    if ($obj[1] != null):
                        foreach ($obj[1] as $promo): ?>
                            <tr>
                                <td>
                                    <a href="/SatellysReborn/promotion/details/<?= $promo->getId() ?>"><?= $promo->getNom() ?></a>
                                </td>
                                <td><?= $promo->getAnnee() ?></td>
                            </tr>
                        <?php endforeach;
                    endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>