<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Connexion déjà établie
        </div>
        <div class="panel-body">
            Vous êtes déjà connecté à l'application, veuillez vous déconnecter avant de vous connecter avec un autre compte.
        </div>
    </div>
</div>