<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Connexion déjà établie
        </div>
        <div class="panel-body">
            Vous êtes déjà connecté, impossible de vous connecter deux fois.<br />
            Veuillez vous déconnecter si vous voulez changer de compte.
        </div>
    </div>
</div>
