<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Identifiants Invalides
        </div>
        <div class="panel-body">
            Les identifiants saisies n'ont pas permis de vous connecter.<br />
            Veuillez réessayer de vous connecter avec des identifiants valides.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>