<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Identifiants Invalides
        </div>
        <div class="panel-body">
            Les identifiants saisies n'ont pas permis de vous connecter.<br />
            Veuillez réessayer de vous connecter avec des identifiants valides.
        </div>
    </div>
</div>