<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : La mise à jour a échoué.
        </div>
        <div class="panel-body">
            La mise à jour de vos information a échoué.<br/>
            Veuillez réessayer.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>