<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

    <div class="container">
        <div class="panel panel-danger">
            <div class="panel-heading">
                Identifiants invalides
            </div>
            <div class="panel-body">
                Les identifiants que vous avez saisies n'ont pas permis de vous connecter.<br/>
                Veuillez saisir des identifiants valides.
            </div>
        </div>
    </div>
<?php

