<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="jumbotron">
                <h2 class="text-center">Mot de passe oublié ?</h2><br/>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <form action="/SatellysReborn/compte/resetMdp/"
                              method="post" id="form-connexion">
                            <div class="form-group">
                                <label for="login">Login :</label>
                                <input type="text" class="form-control"
                                       id="login" name="login"
                                       placeholder="Votre nom d'utilisateur"
                                       required>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-success"
                                       value="Envoyer">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
