<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            Mot de passe ré-initialisé !
        </div>
        <div class="panel-body">
            Vous avez reçu un mail avec un nouveau mot de passe.<br />
            Connectez vous avec ce mot de passe pour le changer.
        </div>
        <div class="panel-footer">
            <a href="/SatellysReborn/" class="btn btn-primary">OK</a>
        </div>
    </div>
</div>