<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Impossible de mettre à jour votre compte
        </div>
        <div class="panel-body">
            La mise à jour de vos informations a échoué, veuillez recommencer l'opération.
        </div>
        <div class="panel-footer">
            <div class="panel-footer">
                <a href="<?= $_SERVER['HTTP_REFERER'] ?>" class="btn btn-primary center-block">Retour</a>
            </div>
        </div>
    </div>
</div>