<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            Informations enregistrées !
        </div>
        <div class="panel-body">
            Les informations de votre compte ont bien été mises à jour.
        </div>
        <div class="panel-footer">
            <a href="/SatellysReborn/compte/" class="btn btn-primary">OK</a>
        </div>
    </div>
</div>