<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;

    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Mon Compte
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-12 col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/compte/modifier" method="post">
                        <div class="form-group">
                            <label for="login">Login</label>
                            <input type="text" id="login" name="login" class="form-control" value="<?= Utilisateur::getUtilisateur()->getLogin() ?>" readonly>
                        </div>
                        <div class="form-group">
                            <label for="mdp">Mot de passe</label>
                            <input type="password" id="mdp" name="mdp" class="form-control" placeholder="Mot de passe" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" class="form-control" placeholder="Email" value="<?= Utilisateur::getUtilisateur()->getEmail() ?>" required>
                        </div>
                        <div class="form-group text-center">
                            <input type="submit" class="btn btn-success" value="Modifier">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
