<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;

?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Mon Compte
        </div>
        <div class="panel-body">
            <form action="/SatellysReborn/compte/modifier/" method="post">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label for="login">Login :</label>
                            <input type="text" name="login" id="login"
                                   class="form-control"
                                   value="<?= Utilisateur::getUtilisateur()
                                                         ->getLogin() ?>"
                                   readonly>
                        </div>
                        <div class="form-group">
                            <label for="mdp">Mot de passe :</label>
                            <input type="password" name="mdp" id="mdp"
                                   placeholder="Votre nouveau mot de passe"
                                   class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="tel">Email
                                :</label>
                            <input type="email" name="email" id="email"
                                   class="form-control"
                                   value="<?= Utilisateur::getUtilisateur()
                                                  ->getEmail() ?>"
                                   placeholder="Votre email"
                                   required>
                        </div>
                    </div>
                    <?php
                        // L'utilisateur courant.
                        $util = null;

                        if (Utilisateur::utilCourantEstAdministratif()) {
                            $util = Utilisateur::getUtilisateur()
                                               ->getAdministratif();
                        } else if (Utilisateur::utilCourantEstEnseignant()) {
                            $util = Utilisateur::getUtilisateur()
                                               ->getEnseignant();
                        }
                    ?>
                    <?php if (!Utilisateur::utilCourantEstSuperAdmin()): ?>
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <label for="id">Identifiant UT1 (13
                                    caractères)
                                    :</label>
                                <input type="text" name="id" id="id"
                                       class="form-control"
                                       value="<?= $util->getId() ?>"
                                       readonly>
                            </div>
                        </div>
                        <div class="col-md-3 col-md-offset-3">
                            <div class="form-group">
                                <label for="nom">Nom
                                    :</label>
                                <input type="text" name="nom" id="nom"
                                       class="form-control"
                                       value="<?= $util->getNom() ?>"
                                       placeholder="Votre nom"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="prenom">Prénom
                                    :</label>
                                <input type="text" name="prenom" id="prenom"
                                       class="form-control"
                                       value="<?= $util->getPrenom() ?>"
                                       placeholder="Votre prénom"
                                       required>
                            </div>
                        </div>
                        <div class="col-md-3 col-md-offset-3">
                            <div class="form-group">
                                <label for="tel">Téléphone
                                    :</label>
                                <input type="text" name="tel" id="tel"
                                       class="form-control"
                                       value="<?= $util->getTel() ?>"
                                       pattern="\d{10}"
                                       placeholder="Votre téléphone"
                                       required>
                            </div>
                        </div>
                        <?php if (Utilisateur::getUtilisateur()
                                             ->estAdministratif()
                        ): ?>
                            <div class="col-md-6 col-md-offset-3">
                                <div class="form-group">
                                    <label for="poste">Poste :</label>
                                    <input type="text" name="poste" id="poste"
                                           class="form-control"
                                           value="<?= $util->getPoste() ?>"
                                           required>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <label for="adresse1">Adresse
                                    :</label>
                                <input type="text" name="adresse1" id="adresse1"
                                       class="form-control"
                                       value="<?= $util->getAdresse()
                                                       ->getAdresse1() ?>"
                                       placeholder="Lieu-dit ..."
                                       required><br/>
                                <input type="text" name="adresse2" id="adresse2"
                                       class="form-control"
                                       value="<?= $util->getAdresse()
                                                       ->getAdresse2() ?>"
                                       placeholder="Adresse 2"
                                ><br/>
                                <input type="text" name="adresse3" id="adresse3"
                                       class="form-control"
                                       placeholder="Adresse 3"
                                       value="<?= $util->getAdresse()
                                                       ->getAdresse3() ?>">
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group">
                                <label for="ville">Code Postal et ville
                                    :</label>
                                <select name="ville" id="ville"
                                        class="form-control select-ville"
                                        required>
                                    <option value="<?= $util->getAdresse()
                                                            ->getVille()
                                                            ->getNumInsee() ?>"><?= $util->getAdresse()
                                                                                         ->getVille()
                                                                                         ->getCodePostal() .
                                                                                    " - " .
                                                                                    $util->getAdresse()
                                                                                         ->getVille()
                                                                                         ->getNom() ?></option>
                                </select>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <input type="submit" class="btn btn-success center-block"
                       value="Modifier">
            </form>
        </div>
    </div>
</div>