<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajouter un absent
        </div>
        <div class="panel-body">
            <div class="row">
                <form action="/SatellysReborn/absence/creer/<?= $obj ?>"
                      method="post">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label for="etudiant">Etudiant :</label>
                            <select name="etudiant" id="etudiant"
                                    class="form-control select-etud-abs" required>
                            </select>
                        </div>
                        <input type="submit"
                               class="btn btn-success center-block"
                               value="Ajouter">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>