<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Créer un groupe
        </div>
        <div class="panel-body">
            <div class="row">
                <form action="/SatellysReborn/groupe/ajouter/<?= $obj ?>" method="post">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label for="etudiant">Etudiant :</label>
                            <select name="etudiant" id="etudiant" class="form-control select-etud" <?= isset($obj[1]) ? 'readonly': '' ?>>
                                <?php if (isset($obj[1])): ?>
                                <option value="<?= $obj[1]->getId() ?>"><?= $obj[1]->getNomComplet() ?></option>
                                <?php endif; ?>
                            </select>
                        </div>
                        <input type="submit" class="btn btn-success center-block" value="Ajouter">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>