<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Importer un fichier CSV
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/groupe/logsCSV/<?= $obj ?>/"
                          method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label for="csv">Fichier CSV :</label>
                            <input type="file" class="form-control" name="csv"
                                   id="csv" accept=".csv" required>
                        </div>
                        <input type="submit"
                               class="btn btn-success center-block"
                               value="Envoyer">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>