<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Impossible d'ajouter cet étudiant au groupe
        </div>
        <div class="panel-body">
            Il est impossible d'ajouter cet étudiant au groupe.<br/>
            Veuillez réessayer.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>