<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Fichier CSV introuvable
        </div>
        <div class="panel-body">
            Le fichier CSV est introuvable, veuillez le re-importer.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>