<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Impossible de supprimer ce groupe
        </div>
        <div class="panel-body">
            Il est impossible de supprimer ce groupe car il possède encore des étudiants.<br/>
            Veuillez supprimer ses étudiants avant de le supprimer.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>