<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Absences
        </div>
        <div class="panel-body">
            <table class="table" data-toggle="table" data-search="true" data-height="300">
                <thead>
                    <tr>
                        <th data-field="date" data-sortable="true">Date</th>
                        <th data-field="debut" data-sortable="true">Heure de début</th>
                        <th data-field="fin" data-sortable="true">Heure de fin</th>
                        <th data-field="matiere" data-sortable="true">Matière</th>
                        <th data-field="justifie" data-sortable="true">Justifié</th>
                        <th data-field="motif" data-sortable="true">Motif</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($obj != null): ?>
                        <?php foreach ($obj as $absence): ?>
                            <tr>
                                <td><?= $absence->getCours()->getJour() ?></td>
                                <td><?= $absence->getCours()->getDebut() ?></td>
                                <td><?= $absence->getCours()->getFin() ?></td>
                                <td><?= $absence->getCours()->getMatiere()->getNom() ?></td>
                                <td><?= $absence->estJustifie() ? 'Oui' : 'Non' ?></td>
                                <td><?= $absence->getMotif() ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
