<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Etudiant inconnu
        </div>
        <div class="panel-body">
            Cet étudiant n'existe pas.
        </div>
        <div class="panel-footer">
            <a href="<?= $_SERVER['HTTP_REFERER'] ?>" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>
