<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Etudiant Inconnu.
        </div>
        <div class="panel-body">
            L'étudiant demandé n'existe pas.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>