<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Liste des étudiants
        </div>
        <div class="panel-body">
            <table data-toggle="table" data-height="800" data-search="true"
                   data-pagination="true">
                <thead>
                <tr>
                    <th data-sortable="true" data-field="idUT1">Identifiant UT1</th>
                    <th data-sortable="true" data-field="ine">Numéro INE</th>
                    <th data-sortable="true" data-field="identite">Identité de l'étudiant</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($obj as $etudiant): ?>
                    <tr>
                        <td><a href="/SatellysReborn/etudiant/details/<?= $etudiant->getId(); ?>"> <?= $etudiant->getId(); ?></a></td>
                        <td><?= $etudiant->getIne(); ?></td>
                        <td><?= $etudiant->getNom()." ".$etudiant->getPrenom();?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
