<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            Ajout réussi !
        </div>
        <div class="panel-body">
            L'administratif à bien été ajouté
        </div>
        <div class="panel-footer">
            <div class="center-block">
                <a href="/SatellysReborn/" class="btn btn-primary">OK</a>
            </div>
        </div>
    </div>
</div>