<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>

<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur d'adresse
        </div>
        <div class="panel-body">
            Une erreur s'est produite lors de la création d'une adresse !
            Veuillez recommencer la saisie !
        </div>
    </div>
</div>
