<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout d'administratif
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/administrateur/ajout"
                          method="post">
                        <div class="form-group">
                            <label for="nom">Nom:</label>
                            <input type="text" class="form-control" name="nom"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="prenom">Prénom:</label>
                            <input type="text" class="form-control"
                                   name="prenom" required>
                        </div>
                        <div class="form-group">
                            <label for="id">Identifiant (13 caractères):</label>
                            <input type="text" class="form-control" name="id"
                                   maxlength="13"
                                   minlength="13" required>
                        </div>
                        <div class="form-group">
                            <label for="tel">Téléphone:</label>
                            <input type="tel" class="form-control" name="tel"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="email">Adresse e-mail:</label>
                            <input type="email" class="form-control"
                                   name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="poste">Poste:</label>
                            <input type="text" class="form-control" name="poste"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="adresse">Adresse:</label>
                            <input type="text" class="form-control"
                                   name="adresse" required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   name="adresse2">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control"
                                   name="adresse3">
                        </div>
                        <div class="form-group">
                            <label for="ville">Ville:</label>
                            <select class="form-control" name="ville" required>
                                <?php
                                    foreach ($obj as $val) {
                                        ?>
                                        <option
                                            value="<?php echo $val->getNumInsee(); ?>"> <?php echo $val->getNom(); ?> </option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </div>
                        <button type="submit"
                                class="btn btn-success center-block">Créer
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
