<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Créer un département
        </div>
        <div class="panel-body">
            <div class="row">
                <form action="/SatellysReborn/promotion/creer/" method="post">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label for="nom">Nom :</label>
                            <input type="text" id="nom" name="nom"
                                   class="form-control" placeholder="Nom de la promotion"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="annee">Année scolaire :</label>
                            <input type="text" id="annee" name="annee"
                                   class="form-control" pattern="\d{4}/\d{4}"
                                   placeholder="Année scolaire" required>
                        </div>
                        <div class="form-group">
                            <label for="dep">Département :</label>
                            <select name="dep" id="dep"
                                    class="form-control select-dep" <?= isset($obj[1]) ?
                                'readonly' : '' ?>>
                                <?php if (isset($obj[1])): ?>
                                    <option
                                        value="<?= $obj[1]->getId() ?>"><?= $obj[1]->getNom() ?></option>
                                <?php endif; ?>
                            </select>
                        </div>
                        <input type="submit"
                               class="btn btn-success center-block"
                               value="Créer">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>