<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Promotion <?= $obj[0]->getNom() ?>
        </div>
        <div class="panel-body">
            <form
                action="/SatellysReborn/promotion/modifier/<?= $obj[0]->getId() ?>/"
                method="post">
                    <div class="row">
                        <div class="col-md-12 toolbar">
                            <div class="btn-group panel-body">
                                <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                                    <a href="/SatellysReborn/groupe/creation/<?= $obj[0]->getId() ?>/"
                                       class="btn btn-success btn-lg"><i
                                            class="fa fa-plus"></i> Ajouter un
                                        groupe</a>
                                    <button type="submit"
                                            class="btn btn-info btn-lg"><i
                                            class="fa fa-edit"></i> Modifier
                                    </button>
                                    <?php if (empty($obj[1])): ?>
                                        <a href="/SatellysReborn/promotion/supprimer/<?= $obj[0]->getId() ?>/"
                                           class="btn btn-danger btn-lg"><i
                                                class="fa fa-remove"></i> Supprimer</a>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <a href="#" id="mail"
                                   class="btn btn-primary btn-lg"><i
                                        class="fa fa-envelope-o"></i> Envoyer</a>
                            </div>
                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-2 col-md-offset-3">
                        <div class="form-group">
                            <label for="id">Identifiant :</label>
                            <input type="text" id="id" class="form-control"
                                   value="<?= $obj[0]->getId() ?>" readonly>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="nom">Nom :</label>
                            <input type="text" id="nom" name="nom"
                                   class="form-control" placeholder="Nom"
                                   value="<?= $obj[0]->getNom() ?>" required>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="annee">Année scolaire :</label>
                            <input type="text" id="annee" name="annee"
                                   class="form-control"
                                   placeholder="Année scolaire"
                                   value="<?= $obj[0]->getAnnee() ?>"
                                   pattern="\d{4}/\d{4}" required>
                        </div>
                    </div>
                </div>
            </form>
            <table data-toggle="table" data-search="true" data-height="800"
                   data-pagination="true" data-page-list="[10, 25, 50, 100, All]">
                <thead>
                <tr>
                    <th data-field="nom" data-sortable="true">Nom</th>
                </tr>
                </thead>
                <tbody>
                <?php
                    if ($obj[1] != null):
                        foreach ($obj[1] as $promo): ?>
                            <tr>
                                <td>
                                    <a href="/SatellysReborn/groupe/details/<?= $promo->getId() ?>"><?= $promo->getNom() ?></a>
                                </td>
                            </tr>
                        <?php endforeach;
                    endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>