<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            Erreur : Impossible de supprimer cette promotion
        </div>
        <div class="panel-body">
            Il est impossible de supprimer cette promotion car elle possède
            encore des groupes d'étudiants.<br/>
            Veuillez supprimer ses groupes avant de la supprimer.
        </div>
        <div class="panel-footer">
            <a href="#" onclick="window.history.back()" class="btn btn-primary">Retour</a>
        </div>
    </div>
</div>