<?php
include_once COMMON . 'header.phtml';
include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="jumbotron">
        <h1>SatellysReborn : Accueil</h1>
        <p>Bonjour et bienvenue sur cette plateforme de gestion d'absence d'élève et de consultation
            d'emploi du temps</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Se connecter</a></p>
    </div>
</div>
