<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout d'enseignant
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="/SatellysReborn/cours/selectCours"
                          method="post">
                        <div class="form-group">
                            <label for="cours">Choix du cours:</label>
                            <select class="form-control" name="cours" required>
                                <?php
                                    foreach ($obj as $val) {
                                        ?>
                                        <option
                                            value="<?php echo $val->getId(); ?>">
                                            <?php
                                                echo $val->getMatiere()
                                                         ->getNom() . " : " .
                                                     $val->getJour() .
                                                     " ( de " .
                                                     $val->getDebut() . " à " .
                                                     $val->getFin() .
                                                     " )";
                                            ?>
                                        </option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-success center-block">Valider
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
