<?php
    use WS_SatellysReborn\BaseDonnees\DAO\DAO_Factory;

    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <form action="cours/selectCours" method="post">
        <div class="form-group">
            <label for="cours">Choix du cours:</label>
            <select class="form-control" name="cours" required>
                <?php
                    foreach ($obj as $val) {
                        ?>
                        <option
                            value="<?php echo $val->getId(); ?>">
                            <?php
                                echo $val->getMatiere()->getNom() . " : " .
                                     $val->getJour() . " ( de " .
                                     $val->getDebut() . " à " . $val->getFin() .
                                     " )";
                            ?>
                        </option>
                        <?php
                    }
                ?>
            </select>
        </div>
        <button type="submit" class="btn btn-default">Valider</button>
    </form>
</div>
