<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;
?>

<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            <?= $obj[0]->getMatiere()->getNom() ?> - <?= $obj[0]->getJour() ?>
            - <?= $obj[0]->getDebut() ?> - <?= $obj[0]->getFin() ?>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 toolbar">
                    <div class="btn-group panel-body">
                        <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                            <a href="/SatellysReborn/absence/creation/<?= $obj[0]->getId() ?>"
                                class="btn btn-success btn-lg"><i
                                class="fa fa-plus"></i>
                                Ajouter un absent</a>
                            <button type="submit" class="btn btn-info btn-lg"><i
                                    class="fa fa-edit"></i> Modifier
                            </button>
                            <a href="#" id="mail"
                               class="btn btn-primary btn-lg"><i
                                    class="fa fa-envelope-o"></i> Envoyer</a>
                            <a href="/SatellysReborn/cours/supprimer/<?= $obj[0]->getId() ?>"" class="btn btn-danger btn-lg"><i
                                    class="fa fa-remove"></i> Supprimer</a>
                        <?php elseif (Utilisateur::utilCourantEstEnseignant() && Utilisateur::getUtilisateur()->getEnseignant()->getId() == $obj[0]->getEnseignant()->getId()): ?>
                            <a href="/SatellysReborn/absence/creation/<?= $obj[0]->getId() ?>"
                               class="btn btn-success btn-lg"><i
                                    class="fa fa-plus"></i>
                                Ajouter un absent</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-3">
                    <div class="form-group">
                        <label for="matiere">Matière :</label>
                        <input type="text" id="matiere" class="form-control"
                               value="<?= $obj[0]->getMatiere()->getNom() ?>">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="salle">Salle :</label>
                        <input type="text" id="salle" class="form-control"
                               value="<?= $obj[0]->getSalle() ?>">
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-3">
                    <div class="form-group">
                        <label for="date">Date :</label>
                        <input type="date" id="date" class="form-control"
                               value="<?= $obj[0]->getJour() ?>">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="debut">Début :</label>
                        <input type="time" id="debut" class="form-control"
                               value="<?= $obj[0]->getDebut() ?>">
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="fin">Fin :</label>
                        <input type="time" id="fin" class="form-control"
                               value="<?= $obj[0]->getFin() ?>">
                    </div>
                </div>
            </div>
            <table data-toggle="table" data-height="800" data-search="true" data-page-list="[10, 25, 50, 100, All]">
                <thead>
                <tr>
                    <th data-field="id" data-sortable="true">Identifiant UT1
                    </th>
                    <th data-field="nom" data-sortable="true">Prénom</th>
                    <th data-field="prenom" data-sortable="true">Nom</th>
                    <th data-field="justifie" data-sortable="true">Justifié</th>
                    <th data-field="motif" data-sortable="true">Motif</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php if ($obj[1] != null):
                    foreach ($obj[1] as $abs): ?>
                        <tr>
                            <td>
                                <a href="/SatellysReborn/etudiant/details/<?= $abs->getEtudiant()
                                                                                  ->getId() ?>"><?= $abs->getEtudiant()
                                                                                                        ->getId() ?></a>
                            </td>
                            <td><?= $abs->getEtudiant()->getNom() ?></td>
                            <td><?= $abs->getEtudiant()->getPrenom() ?></td>
                            <td><?= $abs->estJustifie() ? "Oui" : "Non" ?></td>
                            <td><?= $abs->getMotif() ?></td>
                            <td>
                                <a href="/SatellysReborn/absence/details/<?= $obj[0]->getId() ?>/<?= $abs->getEtudiant()
                                                                                                         ->getId() ?>"
                                   class="btn btn-primary"><i
                                        class="fa fa-sticky-note"></i>
                                    Détails</a></td>
                            <td>
                                <a href="/SatellysReborn/absence/supprimer/<?= $obj[0]->getId() ?>/<?= $abs->getEtudiant()
                                                                                                           ->getId() ?>"
                                   class="btn btn-danger"><i
                                        class="fa fa-remove"></i> Supprimer</a>
                            </td>
                        </tr>
                    <?php endforeach;
                endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>