<?php
    use WS_SatellysReborn\BaseDonnees\DAO\DAO_Factory;

    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <form action="addAbsence" method="post">

        <label for="etudiant">Etudiants absents:</label>
        <table class="table table-bordered">
            <tr>
                <th class="text-center">Absent</th>
                <th class="text-center">Etudiant</th>
                <th class="text-center">Motif</th>
                <th class="text-center">Justifiée</th>
            </tr>
            <?php
                //obj[1] pour l'id de cours
                foreach ($obj[0] as $val) {
                    ?>
                    <tr>
                        <td class="text-center" colspan="4"><?php echo $val->getNom(); ?></td>
                    </tr>
                    <?php
                    foreach ($val->getEtudiants($val->getId()) as $ligne) {
                        ?>
                        <tr>
                            <td><input type="checkbox" name="etudiant[]"
                                       value="<?php echo $ligne->getId(); ?>">
                            </td>
                            <td><?php echo $ligne->getNom() . " " .
                                           $ligne->getPrenom(); ?></td>
                            <td><input type="text" class="form-control" name="motif<?php echo $ligne->getId(); ?>"></td>
                            <td><input type="checkbox" name="justifie<?php echo $ligne->getId(); ?>" value="1"></td>
                        </tr>
                        <?php

                    }
                    ?>

                    <?php

                }
            ?>
        </table>
        <input type="hidden" name="idcours" value="<?php echo $obj[1];?>" />
        <button type="submit" class="btn btn-default">Ajouter</button>
    </form>
</div>