<?php
    include_once COMMON . 'Header.phtml';
    include_once COMMON . 'Menu.phtml';
?>
<div class="container">
    <div class="panel my-panel">
        <div class="panel-heading">
            Ajout d'enseignant
        </div>
        <div class="panel-body">
            <form action="/SatellysReborn/cours/addAbsence" method="post">
                <label for="etudiant">Etudiants absents:</label>
                <table class="table table-bordered">
                    <tr>
                        <th class="text-center">Absent</th>
                        <th class="text-center">Etudiant</th>
                        <th class="text-center">Motif</th>
                        <th class="text-center">Justifiée</th>
                    </tr>
                    <?php
                        foreach ($obj[0] as $val) {
                            ?>
                            <tr>
                                <td class="text-center"
                                    colspan="4"><?php echo $val->getNom(); ?></td>
                            </tr>
                            <?php

                            foreach ($val->getEtudiants($val->getId()) as
                                     $ligne) {
                                $exist = false;
                                for ($j = 0; $j < count($obj[2]); $j++) {
                                    if ($obj[2][$j]->getEtudiant()->getId() ==
                                        $ligne->getId()
                                    ) {
                                        $exist = true;
                                        $motif = $obj[2][$j]->getMotif();
                                        $justif = $obj[2][$j]->estJustifie();
                                    }
                                }

                                if ($exist) {
                                    ?>
                                    <tr>
                                        <input type="hidden" name="idEtudiant[]" value="<?php echo $ligne->getId(); ?>">
                                        <td><input type="checkbox"
                                                   name="etudiant<?php echo $ligne->getId(); ?>"
                                                   value="<?php echo $ligne->getId(); ?>"
                                                   checked>
                                        </td>
                                        <td><?php echo $ligne->getNom() . " " .
                                                       $ligne->getPrenom(); ?></td>
                                        <td><input type="text"
                                                   class="form-control"
                                                   name="motif<?php echo $ligne->getId(); ?>"
                                                   value="<?php echo $motif; ?>">
                                        </td>
                                        <td><input type="checkbox"
                                                   name="justifie<?php echo $ligne->getId(); ?>"
                                                   value="1"<?php
                                                if ($justif) {
                                                    echo "checked";
                                                }
                                            ?>></td>
                                    </tr>
                                    <?php
                                } else {


                                    ?>
                                    <tr>
                                        <input type="hidden" name="idEtudiant[]" value="<?php echo $ligne->getId(); ?>">
                                        <td><input type="checkbox"
                                                   name="etudiant<?php echo $ligne->getId(); ?>"
                                                   value="<?php echo $ligne->getId(); ?>">
                                        </td>
                                        <td><?php echo $ligne->getNom() . " " .
                                                       $ligne->getPrenom(); ?></td>
                                        <td><input type="text"
                                                   class="form-control"
                                                   name="motif<?php echo $ligne->getId(); ?>">
                                        </td>
                                        <td><input type="checkbox"
                                                   name="justifie<?php echo $ligne->getId(); ?>"
                                                   value="1"></td>
                                    </tr>
                                    <?php
                                }
                            }
                        }


                    ?>
                </table>
                <input type="hidden" name="idcours" value="<?php echo $obj[1];?>">
                <input type="submit" class="btn btn-success center-block" value="Ajouter">
            </form>
        </div>
    </div>
</div>