<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="<?= CSS ?>bootstrap.min.css">
        <link rel="stylesheet" href="<?= CSS ?>bootstrap-table.min.css">
        <link rel="stylesheet" href="<?= CSS ?>font-awesome.min.css">
        <link rel="stylesheet" href="<?= CSS ?>select2.min.css">
        <link rel="stylesheet" href="<?= CSS ?>style.css">

        <script type="text/javascript" src="<?= JS ?>jquery-3.1.1.min.js"></script>
        <script type="text/javascript" src="<?= JS ?>bootstrap.min.js"></script>
        <script type="text/javascript" src="<?= JS ?>bootstrap-table.min.js"></script>
        <script type="text/javascript" src="<?= JS ?>bootstrap-table-fr-FR.min.js"></script>
        <script type="text/javascript" src="<?= JS ?>select2.min.js"></script>
        <script type="text/javascript" src="<?= JS ?>select.js"></script>

        <title><?= $this->getTitre() ?></title>
    </head>