<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" type="text/css" href="<?= CSS . 'bootstrap.min.css' ?>">
    <link rel="stylesheet" type="text/css" href="<?= CSS . 'style.css' ?>">

    <script type="text/javascript" src="<?= JS . 'jquery-3.1.1.min.js' ?>"></script>
    <script type="text/javascript" src="<?= JS . 'bootstrap.min.js' ?>"></script>

    <title><?= $this->getTitre() ?></title>
</head>