<?php
    use SatellysReborn\Modeles\Population\Login\Utilisateur;

?>

<body>
<nav class="navbar navbar-fixed-top my-navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/SatellysReborn/"><img src="<?= URL ?>favicon.ico"
                                                                 alt=""> SatellysReborn</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php if (Utilisateur::estConnecte()): ?>
                    <li><a href="/SatellysReborn/departement/">Départements</a></li>
                    <li><a href="/SatellysReborn/promotion/">Promotions</a></li>
                    <li><a href="/SatellysReborn/groupe/">Groupes</a></li>
                    <li><a href="/SatellysReborn/etudiant/">Etudiants</a></li>
                    <li><a href="/SatellysReborn/matiere/">Matières</a></li>
                <?php else: ?>
                    <li><a href="/SatellysReborn/">Accueil</a></li>
                <?php endif; ?>
                <?php if (Utilisateur::utilCourantEstAdmin()): ?>
                    <li><a href="/SatellysReborn/enseignant/">Enseignants</a></li>
                    <li><a href="/SatellysReborn/import/">Import ICS</a></li>
                    <li><a href="/SatellysReborn/cours/creation/">Créer un cours</a></li>
                <?php endif; ?>
                <?php if (Utilisateur::utilCourantEstSuperAdmin()): ?>
                    <li><a href="/SatellysReborn/administratif/">Administratif</a></li>
                <?php endif; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if (Utilisateur::estConnecte()): ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">Bonjour,
                            <strong><?= Utilisateur::getUtilisateur()
                                                   ->getLogin() ?></strong>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/SatellysReborn/compte/"><i
                                        class="fa fa-cogs"></i> Mon Compte</a>
                            </li>
                            <li><a href="/SatellysReborn/compte/deconnexion"><i
                                        class="fa fa-sign-out"></i> Se
                                    Déconnecter</a></li>
                        </ul>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>