<body>
    <div class="container-fluid">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">SatellysReborn</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Accueil <span class="sr-only">(current)</span></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown dropdown-connexion">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Se Connecter <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <form action="">
                                    <li>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="login" placeholder="Login" required>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <input type="password" class="form-control" id="mdp" placeholder="Mot de passe" required>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <input type="submit" class="btn btn-success" name="submit" value="Se Connecter">
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <a href="#" class="btn btn-primary">Mot de passe oublié ?</a>
                                        </div>
                                    </li>
                                </form>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>